### PR TITLE
Global LDAP_DEREF_NEVER should be namespaced

### PR DESCRIPTION
**Pull request by junowilderness**

### CODE REVIEW

**Comment by robertrossmann** [comment]
Thanks! I am no longer actively working on this project anymore and have moved away from PHP quite a long time ago, not even sure how to make a new release now... 🤔

**Comment by cilefen** [comment]
@robertrossmann First - thanks for making this library in the first place. I'd be happy to carefully release 3.1.1 if you give me permissions on the project.

**Comment by robertrossmann** [comment]
@cilefen that would be awesome! I have given you write permissions to the repository, let me know if you need something extra to make the release. Thanks for your help!

**Comment by junowilderness** [comment]
@robertrossmann I'm glad to help. I just merged a few tiny build-related PRs but that's all for now.

**Pull request merged**
